default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hr-til_development

test: &test
  <<: *default
  database: hr-til_test<%=ENV['TEST_ENV_NUMBER']%>

cucumber:
  <<: *test

staging:
  <<: *default
  database: hr-til_staging

production:
  <<: *default
  database: hr-til_production
